/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IVotingOption } from './ivoting-option';
/**
 * 
 * @export
 * @interface IVoting
 */
export interface IVoting {
    /**
     * 
     * @type {string}
     * @memberof IVoting
     */
    id?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IVoting
     */
    endDate?: Date;
    /**
     * 
     * @type {Array<IVotingOption>}
     * @memberof IVoting
     */
    options?: Array<IVotingOption> | null;
    /**
     * 
     * @type {string}
     * @memberof IVoting
     */
    ownerId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IVoting
     */
    startDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof IVoting
     */
    votingTitle?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IVoting
     */
    timeout?: number;
    /**
     * 
     * @type {string}
     * @memberof IVoting
     */
    description?: string | null;
}
