/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateUserResponseData } from './create-user-response-data';
/**
 * 
 * @export
 * @interface CreateUserResponseDocument
 */
export interface CreateUserResponseDocument {
    /**
     * 
     * @type {CreateUserResponseData}
     * @memberof CreateUserResponseDocument
     */
    data?: CreateUserResponseData;
}
