/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetAllBlockchainBallotBoxesResponseDocument } from '../models';
/**
 * BallotBoxApi - axios parameter creator
 * @export
 */
export const BallotBoxApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jsonapiV1BlockchainBallotboxesGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/jsonapi/v1/blockchain/ballotboxes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BallotBoxApi - functional programming interface
 * @export
 */
export const BallotBoxApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1BlockchainBallotboxesGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetAllBlockchainBallotBoxesResponseDocument>>> {
            const localVarAxiosArgs = await BallotBoxApiAxiosParamCreator(configuration).jsonapiV1BlockchainBallotboxesGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BallotBoxApi - factory interface
 * @export
 */
export const BallotBoxApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1BlockchainBallotboxesGet(options?: AxiosRequestConfig): Promise<AxiosResponse<GetAllBlockchainBallotBoxesResponseDocument>> {
            return BallotBoxApiFp(configuration).jsonapiV1BlockchainBallotboxesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BallotBoxApi - object-oriented interface
 * @export
 * @class BallotBoxApi
 * @extends {BaseAPI}
 */
export class BallotBoxApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BallotBoxApi
     */
    public async jsonapiV1BlockchainBallotboxesGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<GetAllBlockchainBallotBoxesResponseDocument>> {
        return BallotBoxApiFp(this.configuration).jsonapiV1BlockchainBallotboxesGet(options).then((request) => request(this.axios, this.basePath));
    }
}
