/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CastVoteRequestDocument } from '../models';
import { CastVoteResponseDocument } from '../models';
import { CreateVotingRequestDocument } from '../models';
import { CreateVotingResponseDocument } from '../models';
import { GetAllVotingsResponseDocument } from '../models';
/**
 * VotingApi - axios parameter creator
 * @export
 */
export const VotingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CastVoteRequestDocument} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jsonapiV1VotingsCastingPost: async (body?: CastVoteRequestDocument, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/jsonapi/v1/votings/casting`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jsonapiV1VotingsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/jsonapi/v1/votings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateVotingRequestDocument} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jsonapiV1VotingsPost: async (body?: CreateVotingRequestDocument, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/jsonapi/v1/votings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VotingApi - functional programming interface
 * @export
 */
export const VotingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CastVoteRequestDocument} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1VotingsCastingPost(body?: CastVoteRequestDocument, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CastVoteResponseDocument>>> {
            const localVarAxiosArgs = await VotingApiAxiosParamCreator(configuration).jsonapiV1VotingsCastingPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1VotingsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetAllVotingsResponseDocument>>> {
            const localVarAxiosArgs = await VotingApiAxiosParamCreator(configuration).jsonapiV1VotingsGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {CreateVotingRequestDocument} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1VotingsPost(body?: CreateVotingRequestDocument, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CreateVotingResponseDocument>>> {
            const localVarAxiosArgs = await VotingApiAxiosParamCreator(configuration).jsonapiV1VotingsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VotingApi - factory interface
 * @export
 */
export const VotingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {CastVoteRequestDocument} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1VotingsCastingPost(body?: CastVoteRequestDocument, options?: AxiosRequestConfig): Promise<AxiosResponse<CastVoteResponseDocument>> {
            return VotingApiFp(configuration).jsonapiV1VotingsCastingPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1VotingsGet(options?: AxiosRequestConfig): Promise<AxiosResponse<GetAllVotingsResponseDocument>> {
            return VotingApiFp(configuration).jsonapiV1VotingsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateVotingRequestDocument} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonapiV1VotingsPost(body?: CreateVotingRequestDocument, options?: AxiosRequestConfig): Promise<AxiosResponse<CreateVotingResponseDocument>> {
            return VotingApiFp(configuration).jsonapiV1VotingsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VotingApi - object-oriented interface
 * @export
 * @class VotingApi
 * @extends {BaseAPI}
 */
export class VotingApi extends BaseAPI {
    /**
     * 
     * @param {CastVoteRequestDocument} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VotingApi
     */
    public async jsonapiV1VotingsCastingPost(body?: CastVoteRequestDocument, options?: AxiosRequestConfig) : Promise<AxiosResponse<CastVoteResponseDocument>> {
        return VotingApiFp(this.configuration).jsonapiV1VotingsCastingPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VotingApi
     */
    public async jsonapiV1VotingsGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<GetAllVotingsResponseDocument>> {
        return VotingApiFp(this.configuration).jsonapiV1VotingsGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {CreateVotingRequestDocument} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VotingApi
     */
    public async jsonapiV1VotingsPost(body?: CreateVotingRequestDocument, options?: AxiosRequestConfig) : Promise<AxiosResponse<CreateVotingResponseDocument>> {
        return VotingApiFp(this.configuration).jsonapiV1VotingsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
