/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ballot } from './ballot';
/**
 * 
 * @export
 * @interface BallotBlock
 */
export interface BallotBlock {
    /**
     * 
     * @type {number}
     * @memberof BallotBlock
     */
    index?: number;
    /**
     * 
     * @type {Date}
     * @memberof BallotBlock
     */
    timeStamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof BallotBlock
     */
    previousHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BallotBlock
     */
    hash?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BallotBlock
     */
    nonce?: number;
    /**
     * 
     * @type {Ballot}
     * @memberof BallotBlock
     */
    data?: Ballot;
}
