/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ballot
 */
export interface Ballot {
    /**
     * 
     * @type {string}
     * @memberof Ballot
     */
    votingId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ballot
     */
    optionId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Ballot
     */
    voteCount?: number;
}
