/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BallotBlock } from './ballot-block';
/**
 * 
 * @export
 * @interface BallotBlockchain
 */
export interface BallotBlockchain {
    /**
     * 
     * @type {Array<BallotBlock>}
     * @memberof BallotBlockchain
     */
    chain?: Array<BallotBlock> | null;
    /**
     * 
     * @type {number}
     * @memberof BallotBlockchain
     */
    difficulty?: number;
}
