/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IUser } from './iuser';
/**
 * 
 * @export
 * @interface CreateUserResponseData
 */
export interface CreateUserResponseData {
    /**
     * 
     * @type {IUser}
     * @memberof CreateUserResponseData
     */
    user?: IUser;
    /**
     * 
     * @type {string}
     * @memberof CreateUserResponseData
     */
    privateKey?: string | null;
}
