/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserBlock } from './user-block';
/**
 * 
 * @export
 * @interface GetAllBlockchainUsersResponseData
 */
export interface GetAllBlockchainUsersResponseData {
    /**
     * 
     * @type {Array<UserBlock>}
     * @memberof GetAllBlockchainUsersResponseData
     */
    userChain?: Array<UserBlock> | null;
}
