/* tslint:disable */
/* eslint-disable */
/**
 * Vokko
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface UserBlock
 */
export interface UserBlock {
    /**
     * 
     * @type {number}
     * @memberof UserBlock
     */
    index?: number;
    /**
     * 
     * @type {Date}
     * @memberof UserBlock
     */
    timeStamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserBlock
     */
    previousHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBlock
     */
    hash?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserBlock
     */
    nonce?: number;
    /**
     * 
     * @type {User}
     * @memberof UserBlock
     */
    data?: User;
}
